export const starryAssets = {
  bibi: "/assets/starry/bibi-the-butterfly.png",
  starryCover: "/assets/starry/starry-camp-front-cover.png",
  starryColouring: "/assets/starry/starry-camp-colouring-page.png",
  bodyMapTemplate: "/assets/starry/starry-camp-body-map-template.png",
  missionPathTemplate: "/assets/starry/starry-camp-mission-path-template.png",
  grownupSupportTemplate: "/assets/starry/starry-camp-grownup-support-template.png",
  certificateTemplate: "/assets/starry/starry-camp-certificate-template.png",
  stickerCampfire: "/assets/starry/starry-camp-sticker-campfire.png",
  stickerClouds: "/assets/starry/starry-camp-sticker-clouds.png",
  stickerMoon: "/assets/starry/starry-camp-sticker-moon.png",
  stickerPath: "/assets/starry/starry-camp-sticker-path.png",
  stickerPineTree: "/assets/starry/starry-camp-sticker-pine-tree.png",
  stickerSparkles: "/assets/starry/starry-camp-sticker-sparkles.png",
  stickerTent: "/assets/starry/starry-camp-sticker-tent.png",
} as const;
